dataset:
    name: facereid

aug:
    resize_size: [96,96] #[128, 128]
    random_mirror: True
    pad: 10
    random_crop: True

train:
    optimizer: 'Adam'
    lr: 0.00035
    num_epochs: 121
    p_size: 8 
    k_size: 4
    sampler: 'triplet'
    wd: 0.0005
    step: [50, 80]
    factor: 0.1
    warmup_epoch: 20
    warmup_begin_lr: 0.0000035
    loss_fn: 'softmax_triplet'


test:
    batch_size: 1 

network:
    name: 'Resnet18'
    last_stride: 1

misc:
    eval_step: 10
    save_step: 10
    log_interval: 20


